### PR TITLE
Fix locales domain 

### PR DESCRIPTION
**Pull request by btry**
Fix locales domain

### CODE REVIEW

**Review by DIOHz0r — APPROVED** [review]
Reviewed

**Comment by ajsb85** [comment]
Hi, @btry 
`/listSearchOptions/PluginOrionReport` still return status 500

**Comment by btry** [comment]
@ajsb85 try again

**Comment by ajsb85** [comment]
@btry Perfect, it's works, Thank you.

**Comment by ajsb85** [comment]
@ajsb85 The listSearchOptions works, but no the Search:

{{base_url}}/search/PluginOrionReport/?forcedisplay[0]=1&forcedisplay[1]=2&uid_cols

Return  "content-range": "0--1/"

**Pull request merged**
